### ISSUE TITLE
New了一个新工程导入没问题可以运行起来,但是添加到公司的项目.报了如下错误 就用不了了

### ISSUE THREAD

**Issue by weixianshishen** [wuhenzhizao/android-sku#13]
android.content.res.Resources$NotFoundException: Unable to find resource ID #0x8
        at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:273)
        at android.content.res.Resources.getResourceEntryName(Resources.java:2005)
        at com.wuhenzhizao.sku.view.SkuItemLayout$ItemClickListener.onClick(Unknown Source:0)
        at android.view.View.performClick(View.java:6266)
        at android.view.View$PerformClick.run(View.java:24730)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by wuhenzhizao** [comment]
资源没找到，好好检查一下代码吧
